//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ManageMasterStock
    {
        [Required]
        public string ItemName { get; set; }
       
        [Required(ErrorMessage = "ItemId must match with ItemMaster")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "ItemId must be a number ")]
      
        public int ItemId { get; set; }
        [ForeignKey("ItemId")]
        public virtual ItemMaster ItemMaster { get; set; }

        public int MasterId { get; set; }
        [Required]
        public Nullable<int> Stock { get; set; }
    }
}
